#!/bin/bash

# Python executable
PYTHON=".venv/bin/python"

# Network rates to process
rates=("1500kbits" "3000kbits" "4500kbits" "6000kbits" "7500kbits" "50000kbits")
provider="dazn"

# Compile supervised experiments
for rate in "${rates[@]}"; do
    bin="src/compiler.py"
    "$PYTHON" "$bin" --folder="$provider/$rate/data" --server="$provider" &
done
wait

# Generate CNAMEs report for supervised experiments
for rate in "${rates[@]}"; do
    bin="src/profiler.py"
    "$PYTHON" "$bin" --folder="$provider/$rate" --server="$provider"
done

# Sample the HAS streaming flows in supervised experiments
for rate in "${rates[@]}"; do
    bin="src/sampler.py"
    "$PYTHON" "$bin" --folder="$provider/$rate" --server="$provider" &
done
wait

# Generate the records to be used when using classification models
for rate in "${rates[@]}"; do
    bin="src/merger.py"
    "$PYTHON" "$bin" --folder="$provider/$rate" --output=src &
done
wait